=== simgrid/simgrid/src/surf/simgrid.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform ((config|random)*,(include|cluster|cabinet|peer|AS|trace|trace_connect)*,(process)*)>
<!ATTLIST platform version CDATA "0.0">

<!ELEMENT include (include|cluster|cabinet|peer|AS|trace|trace_connect)*>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT trace (#PCDATA)>
<!ATTLIST trace id CDATA #REQUIRED>
<!ATTLIST trace file CDATA "">
<!ATTLIST trace periodicity CDATA #REQUIRED>

<!ELEMENT random EMPTY>
<!ATTLIST random id CDATA #REQUIRED>
<!ATTLIST random min CDATA #REQUIRED>
<!ATTLIST random max CDATA #REQUIRED>
<!ATTLIST random mean CDATA #REQUIRED>
<!ATTLIST random std_deviation CDATA #REQUIRED>
<!ATTLIST random seed CDATA "2147483647">
<!ATTLIST random radical CDATA "">
<!ATTLIST random generator (DRAND48|RAND|RNGSTREAM|NONE) "DRAND48">

<!ELEMENT trace_connect EMPTY>
<!ATTLIST trace_connect kind (HOST_AVAIL|POWER|LINK_AVAIL|BANDWIDTH|LATENCY) "HOST_AVAIL">
<!ATTLIST trace_connect trace CDATA #REQUIRED>
<!ATTLIST trace_connect element CDATA #REQUIRED>

<!ELEMENT AS ((prop*),(((AS|include|storage_type|storage|link|cabinet|cluster|peer|trace|trace_connect)*,(ASroute|trace|trace_connect|bypassASroute)*,(trace|trace_connect)*)|((include|storage_type|storage|host|gpu|cabinet|router|link|trace|trace_connect|host_link)*,(route|trace|trace_connect|bypassRoute)*)))>
<!ATTLIST AS id CDATA #REQUIRED>
<!ATTLIST AS routing (Full|Floyd|Dijkstra|DijkstraCache|None|RuleBased|Vivaldi|Cluster) "None">

<!ELEMENT storage_type (prop*)>
<!ATTLIST storage_type id       CDATA #REQUIRED>
<!ATTLIST storage_type model    CDATA #REQUIRED>
<!ATTLIST storage_type size     CDATA #REQUIRED>
<!ATTLIST storage_type content  CDATA "">

<!ELEMENT storage (prop*)>
<!ATTLIST storage id CDATA #REQUIRED>
<!ATTLIST storage typeId CDATA #REQUIRED>
<!ATTLIST storage content  CDATA "">

<!ELEMENT mount EMPTY>
<!ATTLIST mount id CDATA #REQUIRED>
<!ATTLIST mount name CDATA #REQUIRED>

<!ELEMENT mstorage EMPTY>
<!ATTLIST mstorage typeId CDATA #REQUIRED>
<!ATTLIST mstorage name CDATA #REQUIRED>

<!ELEMENT host (prop|mount|mstorage)*>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host core  CDATA "1">
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host coordinates  CDATA "">

<!ELEMENT gpu EMPTY>
<!ATTLIST gpu name CDATA #REQUIRED>

<!ELEMENT host_link EMPTY>
<!ATTLIST host_link id CDATA #REQUIRED>
<!ATTLIST host_link up CDATA #REQUIRED>
<!ATTLIST host_link down CDATA #REQUIRED>

<!ELEMENT cluster EMPTY>
<!ATTLIST cluster id CDATA #REQUIRED>
<!ATTLIST cluster prefix CDATA #REQUIRED>
<!ATTLIST cluster suffix CDATA #REQUIRED>
<!ATTLIST cluster radical CDATA #REQUIRED>
<!ATTLIST cluster power CDATA #REQUIRED>
<!ATTLIST cluster core CDATA "1">
<!ATTLIST cluster bw CDATA #REQUIRED>
<!ATTLIST cluster lat CDATA #REQUIRED>
<!ATTLIST cluster sharing_policy (SHARED|FULLDUPLEX|FATPIPE) "FULLDUPLEX">
<!ATTLIST cluster bb_bw CDATA "">
<!ATTLIST cluster bb_lat CDATA "">
<!ATTLIST cluster bb_sharing_policy (SHARED|FATPIPE) "SHARED">
<!ATTLIST cluster availability_file CDATA "">
<!ATTLIST cluster state_file CDATA "">
<!ATTLIST cluster router_id CDATA "">

<!ELEMENT cabinet EMPTY>
<!ATTLIST cabinet id CDATA #REQUIRED>
<!ATTLIST cabinet prefix CDATA #REQUIRED>
<!ATTLIST cabinet suffix CDATA #REQUIRED>
<!ATTLIST cabinet radical CDATA #REQUIRED>
<!ATTLIST cabinet power CDATA #REQUIRED>
<!ATTLIST cabinet bw CDATA #REQUIRED>
<!ATTLIST cabinet lat CDATA #REQUIRED>

<!ELEMENT peer EMPTY>
<!ATTLIST peer id CDATA #REQUIRED>
<!ATTLIST peer power CDATA #REQUIRED>
<!ATTLIST peer bw_in CDATA #REQUIRED>
<!ATTLIST peer bw_out CDATA #REQUIRED>
<!ATTLIST peer lat CDATA #REQUIRED>
<!ATTLIST peer coordinates CDATA "">
<!ATTLIST peer availability_file CDATA "">
<!ATTLIST peer state_file CDATA "">

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>
<!ATTLIST router coordinates  CDATA "">

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE|FULLDUPLEX) "SHARED">

<!ELEMENT route (link_ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route symmetrical (YES|NO) "YES">

<!ELEMENT ASroute (link_ctn*)>
<!ATTLIST ASroute src CDATA #REQUIRED>
<!ATTLIST ASroute dst CDATA #REQUIRED>
<!ATTLIST ASroute gw_src CDATA #REQUIRED>
<!ATTLIST ASroute gw_dst CDATA #REQUIRED>
<!ATTLIST ASroute symmetrical (YES|NO) "YES">

<!ELEMENT link_ctn EMPTY>
<!ATTLIST link_ctn id CDATA #REQUIRED>
<!ATTLIST link_ctn direction (UP|DOWN|NONE) "NONE">

<!ELEMENT bypassRoute (link_ctn*)>
<!ATTLIST bypassRoute src CDATA #REQUIRED>
<!ATTLIST bypassRoute dst CDATA #REQUIRED>

<!ELEMENT bypassASroute (link_ctn*)>
<!ATTLIST bypassASroute src CDATA #REQUIRED>
<!ATTLIST bypassASroute dst CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_src CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_dst CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">
<!ATTLIST process on_failure (DIE|RESTART) "DIE">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

<!ELEMENT config (prop*)>
<!ATTLIST config id CDATA "">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED> <!-- <!ATTLIST prop key CDATA #REQUIRED> -->
<!ATTLIST prop value CDATA #REQUIRED>

=== simgrid/simgrid/examples/msg/cloud/multicore_plat.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <AS id="siteA" routing="Full">
    <host id="PM0" speed="1E8" core="1"/>
    <host id="PM1" speed="1E8" core="2"/>
    <host id="PM2" speed="1E8" core="4"/>

    <link id="link1" bandwidth="12500000" latency="1E-2" />

    <route src="PM0" dst="PM1"><link_ctn id="link1"/></route>
    <route src="PM0" dst="PM2"><link_ctn id="link1"/></route>
    <route src="PM1" dst="PM2"><link_ctn id="link1"/></route>
  </AS>
</platform>

=== simgrid/simgrid/examples/msg/mc/test/snapshot_comparison_platform.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <host id="HostA" power="137.333mf"/>
   <host id="HostB" power="98.095mf"/>
   <host id="HostC" power="98.095mf"/>
   <host id="HostD" power="98.095mf"/>
   <link id="1" bandwidth="3.430125MBps" latency="536.941us"/>
   <link id="2" bandwidth="3.430125MBps" latency="536.941us"/>
   <link id="3" bandwidth="3.430125MBps" latency="536.941us"/>
   <route src="HostA" dst="HostB"><link_ctn id="1"/></route>
   <route src="HostA" dst="HostC"><link_ctn id="2"/></route>
   <route src="HostA" dst="HostD"><link_ctn id="3"/></route>
 </AS>
 </platform>

=== simgrid/simgrid/examples/platforms/small_platform_profile.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "https://simgrid.org/simgrid.dtd">
<platform version="4.1">
  <zone  id="AS0"  routing="Full">
    <host id="Jupiter"  speed="25Mf" speed_file="profiles/jupiter_speed.profile" />
    <host id="Fafard"   speed="25Mf"/>

    <link id="1" bandwidth="1MBps" latency="10ms" bandwidth_file="profiles/link1_bandwidth.profile" latency_file="profiles/link1_latency.profile" />
    <link id="2" bandwidth="1MBps" latency="10ms"/>

    <route src="Fafard" dst="Jupiter" symmetrical="NO">
      <link_ctn id="1"/>
    </route>
    <route src="Jupiter" dst="Fafard" symmetrical="NO">
      <link_ctn id="2"/>
    </route>
  </zone>
</platform>

=== simgrid/simgrid/examples/msg/parallel_task/test_ptask_deployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <!-- The master process (with some arguments) -->
  <process host="Ginette" function="execute">
     <argument value="Tremblay"/>
     <argument value="Jupiter"/>
     <argument value="Fafard"/> 
     <argument value="Ginette"/>
     <argument value="4e9"/>
     <argument value="16e4"/>
  </process>
  <process host="Ginette" function="redistribute">
    <argument value="Tremblay"/>
    <argument value="Jupiter"/>
    <argument value="Fafard"/> 
    <argument value="Ginette"/>
    <argument value="16e8"/>
  </process>
</platform>

=== simgrid/simgrid/examples/msg/app-chainsend/app-chainsend_d.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <!-- For using with chainsend -->
  <!-- Broadcaster -->
  <process host="node-0.acme.org" function="broadcaster">
    <argument value="8"/> <!-- number of peers -->
    <argument value="256"/> <!-- number of pieces -->
  </process>

  <!-- Peers -->
  <process host="node-1.acme.org" function="peer">
    <argument value="1"/>  </process>
  <process host="node-2.acme.org" function="peer">
    <argument value="2"/>
  </process>
  <process host="node-3.acme.org" function="peer">
    <argument value="3"/>
  </process>
  <process host="node-4.acme.org" function="peer">
    <argument value="4"/>
  </process>
  <process host="node-5.acme.org" function="peer">
    <argument value="5"/>
  </process>
  <process host="node-6.acme.org" function="peer">
    <argument value="6"/>
  </process>
  <process host="node-7.acme.org" function="peer">
    <argument value="7"/>
  </process>
  <process host="node-8.acme.org" function="peer">
    <argument value="8"/>
  </process>
</platform>

=== simgrid/simgrid/examples/basic/deploy.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
  <!-- The master process (with some arguments) -->

  <process host="Jacquelin" function="basic.Master">
     <argument value="10"/>       <!-- Number of tasks -->
     <argument value="50000000"/>  <!-- Computation size of tasks -->
     <argument value="1000000"/>   <!-- Communication size of tasks -->
     <argument value="2"/>  <!-- Number of slaves -->
  </process>
  <!-- The slave process (with no argument) -->
  <process host="Jacquelin" function="basic.Slave"><argument value="0"/></process>
  <process host="Boivin" function="basic.Slave" start_time="5"><argument value="1"/></process>
<!--  <process host="Jean_Yves" function="Slave"><argument value="2"/></process>
  <process host="TeX" function="Slave"><argument value="3"/></process>
  <process host="Geoff" function="Slave"><argument value="4"/></process>
  <process host="Disney" function="Slave"><argument value="5"/></process>
  <process host="iRMX" function="Slave"><argument value="6"/></process>
  <process host="McGee" function="Slave"><argument value="7"/></process>
  <process host="Gatien" function="Slave"><argument value="8"/></process>
  <process host="Laroche" function="Slave"><argument value="9"/></process>
  <process host="Tanguay" function="Slave"><argument value="10"/></process>
  <process host="Morin" function="Slave"><argument value="11"/></process>
  <process host="Ethernet" function="Slave"><argument value="12"/></process>
  <process host="Bellemarre" function="Slave"><argument value="13"/></process>
  <process host="Kuenning" function="Slave"><argument value="14"/></process>
  <process host="Gaston" function="Slave"><argument value="15"/></process>
  <process host="Harry" function="Slave"><argument value="16"/></process>
  <process host="Bousquet" function="Slave"><argument value="17"/></process>
  <process host="Paul" function="Slave"><argument value="18"/></process>
  <process host="St_Jean" function="Slave"><argument value="19"/></process>
  <process host="Jill" function="Slave"><argument value="20"/></process>
  <process host="Marcel" function="Slave"><argument value="21"/></process>
  <process host="Wright" function="Slave"><argument value="22"/></process>
  <process host="Jackson" function="Slave"><argument value="23"/></process>
  <process host="Fernand" function="Slave"><argument value="24"/></process>
  <process host="Soucy" function="Slave"><argument value="25"/></process>
  <process host="Ste_Julie" function="Slave"><argument value="26"/></process>
  <process host="Victoria" function="Slave"><argument value="27"/></process>
  <process host="Lessard" function="Slave"><argument value="28"/></process>
  <process host="Florient" function="Slave"><argument value="29"/></process>
  <process host="Marcoux" function="Slave"><argument value="30"/></process>
  <process host="Gavrel" function="Slave"><argument value="31"/></process>
  <process host="Bescherelle" function="Slave"><argument value="32"/></process>
  <process host="Pierre" function="Slave"><argument value="33"/></process>
  <process host="Jamie" function="Slave"><argument value="34"/></process>
  <process host="Rubin" function="Slave"><argument value="35"/></process>
  <process host="Olivier" function="Slave"><argument value="36"/></process>
  <process host="Boucherville" function="Slave"><argument value="37"/></process>
  <process host="Pointe_Claire" function="Slave"><argument value="38"/></process>
  <process host="Kansas" function="Slave"><argument value="39"/></process>
  <process host="King" function="Slave"><argument value="40"/></process>
  <process host="Lapointe" function="Slave"><argument value="41"/></process>
  <process host="Julian" function="Slave"><argument value="42"/></process>
  <process host="Lafontaine" function="Slave"><argument value="43"/></process>
  <process host="Gordon" function="Slave"><argument value="44"/></process>
  <process host="Drouin" function="Slave"><argument value="45"/></process>
  <process host="Robert" function="Slave"><argument value="46"/></process>
  <process host="Jocelyne" function="Slave"><argument value="47"/></process>
  <process host="Stephen" function="Slave"><argument value="48"/></process>
  <process host="Provost" function="Slave"><argument value="49"/></process>
  <process host="Juneau" function="Slave"><argument value="50"/></process>
  <process host="Casavant" function="Slave"><argument value="51"/></process>
  <process host="St_Antoine" function="Slave"><argument value="52"/></process>
  <process host="Louis" function="Slave"><argument value="53"/></process>
  <process host="Julien" function="Slave"><argument value="54"/></process>
  <process host="St_Paul" function="Slave"><argument value="55"/></process>
  <process host="Mathematica" function="Slave"><argument value="56"/></process>
  <process host="LaTeX" function="Slave"><argument value="57"/></process>
  <process host="Sirois" function="Slave"><argument value="58"/></process>
  <process host="Monique" function="Slave"><argument value="59"/></process>
  <process host="Audy" function="Slave"><argument value="60"/></process>
  <process host="Bourassa" function="Slave"><argument value="61"/></process>
  <process host="OHara" function="Slave"><argument value="62"/></process>
  <process host="Boston" function="Slave"><argument value="63"/></process>
  <process host="Papineau" function="Slave"><argument value="64"/></process>
  <process host="Fraser" function="Slave"><argument value="65"/></process>
  <process host="Browne" function="Slave"><argument value="66"/></process>
  <process host="SunOS" function="Slave"><argument value="67"/></process>
  <process host="Varennes" function="Slave"><argument value="68"/></process>
  <process host="Jacques" function="Slave"><argument value="69"/></process>
  <process host="Thierry" function="Slave"><argument value="70"/></process>
  <process host="Lachapelle" function="Slave"><argument value="71"/></process>
  <process host="kV" function="Slave"><argument value="72"/></process>
  <process host="Yolande" function="Slave"><argument value="73"/></process>
  <process host="Pronovost" function="Slave"><argument value="74"/></process>
  <process host="SPICE" function="Slave"><argument value="75"/></process>
  <process host="Europe" function="Slave"><argument value="76"/></process>
  <process host="Roy" function="Slave"><argument value="77"/></process>
  <process host="Amadeus" function="Slave"><argument value="78"/></process>
  <process host="Intel" function="Slave"><argument value="79"/></process>
  <process host="Cambridge" function="Slave"><argument value="80"/></process>
  <process host="Tremblay" function="Slave"><argument value="81"/></process>
  <process host="UNIX" function="Slave"><argument value="82"/></process>
  <process host="Domey" function="Slave"><argument value="83"/></process>
  <process host="St_Bruno" function="Slave"><argument value="84"/></process>
  <process host="Jean_Claude" function="Slave"><argument value="85"/></process>
  <process host="Doyon" function="Slave"><argument value="86"/></process>
  <process host="Fafard" function="Slave"><argument value="87"/></process>
  <process host="Croteau" function="Slave"><argument value="88"/></process>
  <process host="Dodge" function="Slave"><argument value="89"/></process>
  <process host="Jacquelin" function="Slave"><argument value="90"/></process>
  <process host="Boivin" function="Slave"><argument value="91"/></process>
  <process host="Jean_Yves" function="Slave"><argument value="92"/></process>
  <process host="TeX" function="Slave"><argument value="93"/></process>
  <process host="Geoff" function="Slave"><argument value="94"/></process>
  <process host="Disney" function="Slave"><argument value="95"/></process>
  <process host="iRMX" function="Slave"><argument value="96"/></process>
  <process host="McGee" function="Slave"><argument value="97"/></process>
  <process host="Gatien" function="Slave"><argument value="98"/></process>
  <process host="Laroche" function="Slave"><argument value="99"/></process>
  <process host="Tanguay" function="Slave"><argument value="100"/></process> -->
</platform>

=== simgrid/simgrid/examples/lua/multi_matrix/quicksort_platform.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <!-- ljlkj -->
   <host id="Inmos" power="98.095mf"/>
   <host id="Bellevue" power="76.296mf"/>
   <host id="Fafard" power="76.296mf"/>
   <host id="Ginette" power="48.492mf"/>
   <host id="Bourassa" power="48.492mf"/>
   <link id="6" bandwidth="41.279125MBps" latency="59.904us"/>
   <link id="11" bandwidth="252.75KBps" latency="5.70455ms"/>
   <link id="3" bandwidth="34.285625MBps" latency="514.433us"/>
   <link id="7" bandwidth="11.618875MBps" latency="189.98us"/>
   <link id="9" bandwidth="7.20975MBps" latency="1.461517ms"/>
   <link id="12" bandwidth="1.792625MBps" latency="7.877863ms"/>
   <link id="2" bandwidth="118.6825MBps" latency="136.931us"/>
   <link id="8" bandwidth="8.158MBps" latency="270.544us"/>
   <link id="1" bandwidth="34.285625MBps" latency="514.433us"/>
   <link id="4" bandwidth="10.099625MBps" latency="479.78us"/>
   <link id="0" bandwidth="41.279125MBps" latency="59.904us"/>
   <link id="10" bandwidth="4.67975MBps" latency="848.712us"/>
   <link id="5" bandwidth="27.94625MBps" latency="278.066us"/>
   <link id="loopback_FATPIPE" bandwidth="10MBps" latency="100ms" sharing_policy="FATPIPE"/>
   <link id="loopback" bandwidth="498MBps" latency="15us"/>
   <route src="Inmos" dst="Inmos"><link_ctn id="loopback"/></route>
   <route src="Bellevue" dst="Bellevue"><link_ctn id="loopback"/></route>
   <route src="Fafard" dst="Fafard"><link_ctn id="loopback"/></route>
   <route src="Ginette" dst="Ginette"><link_ctn id="loopback"/></route>
   <route src="Bourassa" dst="Bourassa"><link_ctn id="loopback"/></route>
   <route src="Inmos" dst="Bellevue">
     <link_ctn id="9"/>
   </route>
   <route src="Inmos" dst="Fafard">
     <link_ctn id="4"/><link_ctn id="3"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="8"/>
   </route>
   <route src="Inmos" dst="Ginette">
     <link_ctn id="4"/><link_ctn id="3"/><link_ctn id="5"/>
   </route>
   <route src="Inmos" dst="Bourassa">
     <link_ctn id="4"/><link_ctn id="3"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="6"/><link_ctn id="7"/>
   </route>
   <route src="Bellevue" dst="Fafard">
     <link_ctn id="9"/><link_ctn id="4"/><link_ctn id="3"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="8"/>
   </route>
   <route src="Bellevue" dst="Ginette">
     <link_ctn id="9"/><link_ctn id="4"/><link_ctn id="3"/><link_ctn id="5"/>
   </route>
   <route src="Bellevue" dst="Bourassa">
     <link_ctn id="9"/><link_ctn id="4"/><link_ctn id="3"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="6"/><link_ctn id="7"/>
   </route>
   <route src="Fafard" dst="Ginette">
     <link_ctn id="8"/><link_ctn id="1"/><link_ctn id="0"/><link_ctn id="2"/><link_ctn id="5"/>
   </route>
   <route src="Fafard" dst="Bourassa">
     <link_ctn id="8"/><link_ctn id="6"/><link_ctn id="7"/>
   </route>
   <route src="Ginette" dst="Bourassa">
     <link_ctn id="5"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="6"/><link_ctn id="7"/>
   </route>
 </AS>
 </platform>

=== simgrid/simgrid/examples/platforms/wifi_ns3.xml
<?xml version='1.0'?><!DOCTYPE platform SYSTEM "https://simgrid.org/simgrid.dtd">
<platform version="4.1">
	<config>
		<prop id = "network/model" value = "ns-3" />
	</config>
	<zone id="world" routing="Floyd">

		<zone id="SSID_1" routing="WIFI">
			<prop id="access_point" value="alice"/>
			<prop id="mcs" value="2"/> <!-- Optionnal: default = 3 -->
			<prop id="nss" value="2"/> <!-- Optionnal: default = 1 -->

			<host id="alice" speed="1Gf"/>

			<host id="STA0-0" speed="1Gf">
				<prop id="wifi_distance" value="37"/> <!-- Optionnal: default = 10 -->
			</host>
			<host id="STA0-1" speed="1Gf"/> 
		</zone>

		<zone id="SSID_2" routing="WIFI">
			<prop id="access_point" value="bob"/>

			<router id="bob"/>

			<host id="STA1-0" speed="1Gf"/>
			<host id="STA1-1" speed="1Gf"/>
			<host id="STA1-2" speed="1Gf"/>
		</zone>

		<link id="wireline" bandwidth="100Mbps" latency="2ms" sharing_policy="SHARED"/>

		<zoneRoute src="SSID_1" dst="SSID_2" gw_src="alice" gw_dst="bob">
			<link_ctn id="wireline"/>
		</zoneRoute>
	</zone>
</platform>
