=== simgrid/simgrid/src/surf/simgrid.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform ((config|random)*,(include|cluster|cabinet|peer|AS|trace|trace_connect)*,(process)*)>
<!ATTLIST platform version CDATA "0.0">

<!ELEMENT include (include|cluster|cabinet|peer|AS|trace|trace_connect)*>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT trace (#PCDATA)>
<!ATTLIST trace id CDATA #REQUIRED>
<!ATTLIST trace file CDATA "">
<!ATTLIST trace periodicity CDATA #REQUIRED>

<!ELEMENT random EMPTY>
<!ATTLIST random id CDATA #REQUIRED>
<!ATTLIST random min CDATA #REQUIRED>
<!ATTLIST random max CDATA #REQUIRED>
<!ATTLIST random mean CDATA #REQUIRED>
<!ATTLIST random std_deviation CDATA #REQUIRED>
<!ATTLIST random seed CDATA "2147483647">
<!ATTLIST random radical CDATA "">
<!ATTLIST random generator (DRAND48|RAND|RNGSTREAM|NONE) "DRAND48">

<!ELEMENT trace_connect EMPTY>
<!ATTLIST trace_connect kind (HOST_AVAIL|POWER|LINK_AVAIL|BANDWIDTH|LATENCY) "HOST_AVAIL">
<!ATTLIST trace_connect trace CDATA #REQUIRED>
<!ATTLIST trace_connect element CDATA #REQUIRED>

<!ELEMENT AS ((prop*),(((AS|include|storage_type|storage|link|cabinet|cluster|peer|trace|trace_connect)*,(ASroute|trace|trace_connect|bypassASroute)*,(trace|trace_connect)*)|((include|storage_type|storage|host|gpu|cabinet|router|link|trace|trace_connect|host_link)*,(route|trace|trace_connect|bypassRoute)*)))>
<!ATTLIST AS id CDATA #REQUIRED>
<!ATTLIST AS routing (Full|Floyd|Dijkstra|DijkstraCache|None|RuleBased|Vivaldi|Cluster) "None">

<!ELEMENT storage_type (prop*)>
<!ATTLIST storage_type id       CDATA #REQUIRED>
<!ATTLIST storage_type model    CDATA #REQUIRED>
<!ATTLIST storage_type size     CDATA #REQUIRED>
<!ATTLIST storage_type content  CDATA "">

<!ELEMENT storage (prop*)>
<!ATTLIST storage id CDATA #REQUIRED>
<!ATTLIST storage typeId CDATA #REQUIRED>
<!ATTLIST storage content  CDATA "">

<!ELEMENT mount EMPTY>
<!ATTLIST mount id CDATA #REQUIRED>
<!ATTLIST mount name CDATA #REQUIRED>

<!ELEMENT mstorage EMPTY>
<!ATTLIST mstorage typeId CDATA #REQUIRED>
<!ATTLIST mstorage name CDATA #REQUIRED>

<!ELEMENT host (prop|mount|mstorage)*>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host core  CDATA "1">
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host coordinates  CDATA "">

<!ELEMENT gpu EMPTY>
<!ATTLIST gpu name CDATA #REQUIRED>

<!ELEMENT host_link EMPTY>
<!ATTLIST host_link id CDATA #REQUIRED>
<!ATTLIST host_link up CDATA #REQUIRED>
<!ATTLIST host_link down CDATA #REQUIRED>

<!ELEMENT cluster EMPTY>
<!ATTLIST cluster id CDATA #REQUIRED>
<!ATTLIST cluster prefix CDATA #REQUIRED>
<!ATTLIST cluster suffix CDATA #REQUIRED>
<!ATTLIST cluster radical CDATA #REQUIRED>
<!ATTLIST cluster power CDATA #REQUIRED>
<!ATTLIST cluster core CDATA "1">
<!ATTLIST cluster bw CDATA #REQUIRED>
<!ATTLIST cluster lat CDATA #REQUIRED>
<!ATTLIST cluster sharing_policy (SHARED|FULLDUPLEX|FATPIPE) "FULLDUPLEX">
<!ATTLIST cluster bb_bw CDATA "">
<!ATTLIST cluster bb_lat CDATA "">
<!ATTLIST cluster bb_sharing_policy (SHARED|FATPIPE) "SHARED">
<!ATTLIST cluster availability_file CDATA "">
<!ATTLIST cluster state_file CDATA "">
<!ATTLIST cluster router_id CDATA "">

<!ELEMENT cabinet EMPTY>
<!ATTLIST cabinet id CDATA #REQUIRED>
<!ATTLIST cabinet prefix CDATA #REQUIRED>
<!ATTLIST cabinet suffix CDATA #REQUIRED>
<!ATTLIST cabinet radical CDATA #REQUIRED>
<!ATTLIST cabinet power CDATA #REQUIRED>
<!ATTLIST cabinet bw CDATA #REQUIRED>
<!ATTLIST cabinet lat CDATA #REQUIRED>

<!ELEMENT peer EMPTY>
<!ATTLIST peer id CDATA #REQUIRED>
<!ATTLIST peer power CDATA #REQUIRED>
<!ATTLIST peer bw_in CDATA #REQUIRED>
<!ATTLIST peer bw_out CDATA #REQUIRED>
<!ATTLIST peer lat CDATA #REQUIRED>
<!ATTLIST peer coordinates CDATA "">
<!ATTLIST peer availability_file CDATA "">
<!ATTLIST peer state_file CDATA "">

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>
<!ATTLIST router coordinates  CDATA "">

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE|FULLDUPLEX) "SHARED">

<!ELEMENT route (link_ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route symmetrical (YES|NO) "YES">

<!ELEMENT ASroute (link_ctn*)>
<!ATTLIST ASroute src CDATA #REQUIRED>
<!ATTLIST ASroute dst CDATA #REQUIRED>
<!ATTLIST ASroute gw_src CDATA #REQUIRED>
<!ATTLIST ASroute gw_dst CDATA #REQUIRED>
<!ATTLIST ASroute symmetrical (YES|NO) "YES">

<!ELEMENT link_ctn EMPTY>
<!ATTLIST link_ctn id CDATA #REQUIRED>
<!ATTLIST link_ctn direction (UP|DOWN|NONE) "NONE">

<!ELEMENT bypassRoute (link_ctn*)>
<!ATTLIST bypassRoute src CDATA #REQUIRED>
<!ATTLIST bypassRoute dst CDATA #REQUIRED>

<!ELEMENT bypassASroute (link_ctn*)>
<!ATTLIST bypassASroute src CDATA #REQUIRED>
<!ATTLIST bypassASroute dst CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_src CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_dst CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">
<!ATTLIST process on_failure (DIE|RESTART) "DIE">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

<!ELEMENT config (prop*)>
<!ATTLIST config id CDATA "">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED> <!-- <!ATTLIST prop key CDATA #REQUIRED> -->
<!ATTLIST prop value CDATA #REQUIRED>

=== simgrid/simgrid/examples/java/kademlia/kademlia.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <process host="Jacquelin" function="kademlia.Node">
    <argument value="0"/>        <!-- my id -->
    <argument value ="900"/>     <!-- deadline -->
  </process>
  <process host="Boivin" function="kademlia.Node">
    <argument value="1"/>        <!-- my id -->
    <argument value="0"/>        <!-- known id -->
    <argument value ="900"/>     <!-- deadline -->
  </process>
  <process host="Jean_Yves" function="kademlia.Node">
    <argument value="2"/>        <!-- my id -->
    <argument value="0"/>        <!-- known id -->
    <argument value ="900"/>     <!-- deadline -->
  </process>
  <process host="TeX" function="kademlia.Node">
    <argument value="4"/>        <!-- my id -->
    <argument value="0"/>        <!-- known id -->
    <argument value ="900"/>     <!-- deadline -->  
  </process>
</platform>

=== simgrid/simgrid/examples/msg/gtnets/dogbone-d.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="3">

  <process host="S1" function="master">
      <argument value="10000"/>
      <argument value="C1"/>
      <argument value="0"/>
  </process>

  <process host="S2" function="master">
      <argument value="10000"/>
      <argument value="C2"/>
      <argument value="1"/>
  </process>

  <process host="C1" function="slave">
      <argument value="0"/>
  </process>
  <process host="C2" function="slave">
      <argument value="1"/>
  </process>
</platform>

=== simgrid/simgrid/teshsuite/simdag/platforms/two_hosts_multi_hop.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <host id="bob" power="1000000000"/>
   <host id="alice" power="500000000"/>
 
   <link id="link_bob" bandwidth="125000000" latency="5E-5"/>
   <link id="link_alice" bandwidth="125000000" latency="5E-5"/>
   <link id="switch" bandwidth="125000000" latency="5E-5"
         sharing_policy="FATPIPE"/>
 
   <route src="bob" dst="alice">
     <link_ctn id="link_bob"/>
     <link_ctn id="switch"/>
     <link_ctn id="link_alice"/>
   </route>
 </AS>
 </platform>

=== simgrid/simgrid/examples/msg/masterslave/deployment_masterslave_vivaldi.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="3">


  <!-- The master process (with some arguments) --> 
  <process host="100030591" function="master">
       <argument value="20"/>       <!-- Number of tasks -->
       <argument value="50000000"/>  <!-- Computation size of tasks -->
       <argument value="1000000"/>   <!-- Communication size of tasks -->
       <argument value="39"/>         <!-- Number of slaves -->
    </process>
    <!-- The slave processes (with mailbox to listen on as argument) -->
    <process host="100036570" function="slave">
      <argument value="0"/>
    </process>
    <process host="100041334" function="slave">
      <argument value="1"/>
    </process>
    <process host="100055671" function="slave">
      <argument value="2"/>
    </process>
    <process host="100066658" function="slave">
      <argument value="3"/>
    </process>
    <process host="100090691" function="slave">
      <argument value="4"/>
    </process>
    <process host="100094952" function="slave">
      <argument value="5"/>
    </process>
    <process host="100117943" function="slave">
      <argument value="6"/>
    </process>
    <process host="100126290" function="slave">
      <argument value="7"/>
    </process>
    <process host="100144483" function="slave">
      <argument value="8"/>
    </process>
    <process host="100152889" function="slave">
      <argument value="9"/>
    </process>
    <process host="100178474" function="slave">
      <argument value="10"/>
    </process>
    <process host="100180261" function="slave">
      <argument value="11"/>
    </process>
    <process host="100185883" function="slave">
      <argument value="12"/>
    </process>
    <process host="100186365" function="slave">
      <argument value="13"/>
    </process>
    <process host="100200866" function="slave">
      <argument value="14"/>
    </process>
    <process host="100207885" function="slave">
      <argument value="15"/>
    </process>
    <process host="100224447" function="slave">
      <argument value="16"/>
    </process>
    <process host="100238799" function="slave">
      <argument value="17"/>
    </process>
    <process host="100273297" function="slave">
      <argument value="18"/>
    </process>
    <process host="100280711" function="slave">
      <argument value="19"/>
    </process>
    <process host="100284574" function="slave">
      <argument value="20"/>
    </process>
    <process host="100292843" function="slave">
      <argument value="21"/>
    </process>
    <process host="100309685" function="slave">
      <argument value="22"/>
    </process>
    <process host="100315281" function="slave">
      <argument value="23"/>
    </process>
    <process host="100317715" function="slave">
      <argument value="24"/>
    </process>
    <process host="100324694" function="slave">
      <argument value="25"/>
    </process>
    <process host="100326641" function="slave">
      <argument value="26"/>
    </process>
    <process host="100331484" function="slave">
      <argument value="27"/>
    </process>
    <process host="100347816" function="slave">
      <argument value="28"/>
    </process>
    <process host="100354536" function="slave">
      <argument value="29"/>
    </process>
    <process host="100355017" function="slave">
      <argument value="30"/>
    </process>
    <process host="100359203" function="slave">
      <argument value="31"/>
    </process>
    <process host="100379397" function="slave">
      <argument value="32"/>
    </process>
    <process host="100404046" function="slave">
      <argument value="33"/>
    </process>
    <process host="100413314" function="slave">
      <argument value="34"/>
    </process>
    <process host="100416828" function="slave">
      <argument value="35"/>
    </process>
    <process host="100422926" function="slave">
      <argument value="36"/>
    </process>
    <process host="100427449" function="slave">
      <argument value="37"/>
    </process>
    <process host="100429957" function="slave">
      <argument value="38"/>
    </process>
  </platform>

=== simgrid/simgrid/examples/platforms/hosts_with_disks.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "https://simgrid.org/simgrid.dtd">
<platform version="4.1">
  <zone id="AS0" routing="Full">
    <host id="bob" speed="1Gf">
      <disk id="Disk1" read_bw="100MBps" write_bw="40MBps">
        <prop id="size" value="500GiB"/>
        <prop id="mount" value="/scratch"/>
        <prop id="content" value="storage/content/storage_content.txt"/>
      </disk>
      <disk id="Disk2" read_bw="200MBps" write_bw="80MBps"/>
    </host>

    <host id="alice" speed="1Gf">
      <disk id="Disk1" read_bw="200MBps" write_bw="80MBps">
        <prop id="content" value="storage/content/small_content.txt"/>
      </disk>
    </host>

    <host id="carl" speed="1Gf">
      <prop id="remote_disk" value="/scratch:Disk1:bob"/>
    </host>

    <link id="link1" bandwidth="125MBps" latency="150us" />
    <link id="link2" bandwidth="125MBps" latency="150us" />
    <link id="link3" bandwidth="125MBps" latency="150us" />

    <route src="bob" dst="alice">
      <link_ctn id="link1" />
    </route>
    <route src="bob" dst="carl">
      <link_ctn id="link2" />
    </route>
    <route src="alice" dst="carl">
      <link_ctn id="link3" />
    </route>
  </zone>
</platform>

=== simgrid/simgrid/teshsuite/simdag/platforms/properties.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
	
<config id="General">
	<prop id="maxmin/precision" value="0.000010"></prop>
	<prop id="cpu/optim" value="TI"></prop>
	<prop id="workstation/model" value="compound"></prop>
	<prop id="network/model" value="Vegas"></prop>
	<prop id="path" value="~/"></prop>
</config>
	
<AS  id="AS0"  routing="Full">
	<host id="bob" power="500mf"/>
</AS>
</platform>

=== simgrid/simgrid/examples/msg/irc_isend/deployment_peer01.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">
  <!-- The master process (with some arguments) -->
  <process host="Tremblay" function="sender">
     <argument value="3"/>       <!-- Number of tasks -->
     <argument value="50000000"/>  <!-- Computation size of tasks -->
     <argument value="1000000"/>   <!-- Communication size of tasks -->
     <argument value="1"/>         <!-- Number of receivers -->
     <argument value="5"/>         <!-- Sleep_start_time -->
     <argument value="0.1"/>      <!-- Time for test -->
  </process>
  <!-- The receiver processes -->
  <process host="Ruby" function="receiver">
    <argument value="0"/>
    <argument value="1"/>         <!-- Sleep_start_time -->
    <argument value="0.1"/>      <!-- Time for test -->
  </process>
</platform>

=== simgrid/simgrid/doc/gtut-files/gtut-platform.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "simgrid.dtd">
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <host id="Jacquelin" power="137333000"/>
   <host id="Boivin" power="98095000"/>
   <link id="1" bandwidth="3430125" latency="0.000536941"/>
   <route src="Jacquelin" dst="Boivin"><link_ctn id="1"/></route>
   <route src="Boivin" dst="Jacquelin"><link_ctn id="1"/></route>
 </AS>
 </platform>
