=== simgrid/simgrid/src/surf/simgrid.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform ((config|random)*,(include|cluster|cabinet|peer|AS|trace|trace_connect)*,(process)*)>
<!ATTLIST platform version CDATA "0.0">

<!ELEMENT include (include|cluster|cabinet|peer|AS|trace|trace_connect)*>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT trace (#PCDATA)>
<!ATTLIST trace id CDATA #REQUIRED>
<!ATTLIST trace file CDATA "">
<!ATTLIST trace periodicity CDATA #REQUIRED>

<!ELEMENT random EMPTY>
<!ATTLIST random id CDATA #REQUIRED>
<!ATTLIST random min CDATA #REQUIRED>
<!ATTLIST random max CDATA #REQUIRED>
<!ATTLIST random mean CDATA #REQUIRED>
<!ATTLIST random std_deviation CDATA #REQUIRED>
<!ATTLIST random seed CDATA "2147483647">
<!ATTLIST random radical CDATA "">
<!ATTLIST random generator (DRAND48|RAND|RNGSTREAM|NONE) "DRAND48">

<!ELEMENT trace_connect EMPTY>
<!ATTLIST trace_connect kind (HOST_AVAIL|POWER|LINK_AVAIL|BANDWIDTH|LATENCY) "HOST_AVAIL">
<!ATTLIST trace_connect trace CDATA #REQUIRED>
<!ATTLIST trace_connect element CDATA #REQUIRED>

<!ELEMENT AS ((prop*),(((AS|include|storage_type|storage|link|cabinet|cluster|peer|trace|trace_connect)*,(ASroute|trace|trace_connect|bypassASroute)*,(trace|trace_connect)*)|((include|storage_type|storage|host|gpu|cabinet|router|link|trace|trace_connect|host_link)*,(route|trace|trace_connect|bypassRoute)*)))>
<!ATTLIST AS id CDATA #REQUIRED>
<!ATTLIST AS routing (Full|Floyd|Dijkstra|DijkstraCache|None|RuleBased|Vivaldi|Cluster) "None">

<!ELEMENT storage_type (prop*)>
<!ATTLIST storage_type id       CDATA #REQUIRED>
<!ATTLIST storage_type model    CDATA #REQUIRED>
<!ATTLIST storage_type size     CDATA #REQUIRED>
<!ATTLIST storage_type content  CDATA "">

<!ELEMENT storage (prop*)>
<!ATTLIST storage id CDATA #REQUIRED>
<!ATTLIST storage typeId CDATA #REQUIRED>
<!ATTLIST storage content  CDATA "">

<!ELEMENT mount EMPTY>
<!ATTLIST mount id CDATA #REQUIRED>
<!ATTLIST mount name CDATA #REQUIRED>

<!ELEMENT mstorage EMPTY>
<!ATTLIST mstorage typeId CDATA #REQUIRED>
<!ATTLIST mstorage name CDATA #REQUIRED>

<!ELEMENT host (prop|mount|mstorage)*>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host core  CDATA "1">
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host coordinates  CDATA "">

<!ELEMENT gpu EMPTY>
<!ATTLIST gpu name CDATA #REQUIRED>

<!ELEMENT host_link EMPTY>
<!ATTLIST host_link id CDATA #REQUIRED>
<!ATTLIST host_link up CDATA #REQUIRED>
<!ATTLIST host_link down CDATA #REQUIRED>

<!ELEMENT cluster EMPTY>
<!ATTLIST cluster id CDATA #REQUIRED>
<!ATTLIST cluster prefix CDATA #REQUIRED>
<!ATTLIST cluster suffix CDATA #REQUIRED>
<!ATTLIST cluster radical CDATA #REQUIRED>
<!ATTLIST cluster power CDATA #REQUIRED>
<!ATTLIST cluster core CDATA "1">
<!ATTLIST cluster bw CDATA #REQUIRED>
<!ATTLIST cluster lat CDATA #REQUIRED>
<!ATTLIST cluster sharing_policy (SHARED|FULLDUPLEX|FATPIPE) "FULLDUPLEX">
<!ATTLIST cluster bb_bw CDATA "">
<!ATTLIST cluster bb_lat CDATA "">
<!ATTLIST cluster bb_sharing_policy (SHARED|FATPIPE) "SHARED">
<!ATTLIST cluster availability_file CDATA "">
<!ATTLIST cluster state_file CDATA "">
<!ATTLIST cluster router_id CDATA "">

<!ELEMENT cabinet EMPTY>
<!ATTLIST cabinet id CDATA #REQUIRED>
<!ATTLIST cabinet prefix CDATA #REQUIRED>
<!ATTLIST cabinet suffix CDATA #REQUIRED>
<!ATTLIST cabinet radical CDATA #REQUIRED>
<!ATTLIST cabinet power CDATA #REQUIRED>
<!ATTLIST cabinet bw CDATA #REQUIRED>
<!ATTLIST cabinet lat CDATA #REQUIRED>

<!ELEMENT peer EMPTY>
<!ATTLIST peer id CDATA #REQUIRED>
<!ATTLIST peer power CDATA #REQUIRED>
<!ATTLIST peer bw_in CDATA #REQUIRED>
<!ATTLIST peer bw_out CDATA #REQUIRED>
<!ATTLIST peer lat CDATA #REQUIRED>
<!ATTLIST peer coordinates CDATA "">
<!ATTLIST peer availability_file CDATA "">
<!ATTLIST peer state_file CDATA "">

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>
<!ATTLIST router coordinates  CDATA "">

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE|FULLDUPLEX) "SHARED">

<!ELEMENT route (link_ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route symmetrical (YES|NO) "YES">

<!ELEMENT ASroute (link_ctn*)>
<!ATTLIST ASroute src CDATA #REQUIRED>
<!ATTLIST ASroute dst CDATA #REQUIRED>
<!ATTLIST ASroute gw_src CDATA #REQUIRED>
<!ATTLIST ASroute gw_dst CDATA #REQUIRED>
<!ATTLIST ASroute symmetrical (YES|NO) "YES">

<!ELEMENT link_ctn EMPTY>
<!ATTLIST link_ctn id CDATA #REQUIRED>
<!ATTLIST link_ctn direction (UP|DOWN|NONE) "NONE">

<!ELEMENT bypassRoute (link_ctn*)>
<!ATTLIST bypassRoute src CDATA #REQUIRED>
<!ATTLIST bypassRoute dst CDATA #REQUIRED>

<!ELEMENT bypassASroute (link_ctn*)>
<!ATTLIST bypassASroute src CDATA #REQUIRED>
<!ATTLIST bypassASroute dst CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_src CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_dst CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">
<!ATTLIST process on_failure (DIE|RESTART) "DIE">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

<!ELEMENT config (prop*)>
<!ATTLIST config id CDATA "">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED> <!-- <!ATTLIST prop key CDATA #REQUIRED> -->
<!ATTLIST prop value CDATA #REQUIRED>

=== simgrid/simgrid/teshsuite/simdag/platforms/four_hosts_floyd.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <AS  id="AS0"  routing="Floyd">
    <host id="host1" speed="1Gf"/>
    <host id="host2" speed="1Gf"/>
    <host id="host3" speed="1Gf"/>
    <host id="host4" speed="1Gf"/>

    <link id="link1" bandwidth="125MBps" latency="50us"/>
    <link id="link2" bandwidth="125MBps" latency="50us"/>
    <link id="link3" bandwidth="125MBps" latency="50us"/>
    <link id="link4" bandwidth="125MBps" latency="50us"/>  

    <route src="host1" dst="host2"><link_ctn id="link1"/></route>
    <route src="host1" dst="host3"><link_ctn id="link2"/></route>
    <route src="host2" dst="host3"><link_ctn id="link3"/></route>
    <route src="host3" dst="host4"><link_ctn id="link4"/></route>
  </AS>
</platform>

=== simgrid/simgrid/examples/java/bittorrent/bittorrent.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <process host="Jacquelin" function="bittorrent.Tracker">
    <argument value="3000" />
  </process>

  <process host="Boivin" function="bittorrent.Peer">
    <argument value="00000002"/>      <!-- my id -->
    <argument value="5000" />      <!-- end time -->
    <argument value="1" />     <!-- indicates if the bittorrent.Peer is a seed at the begining of the simulation -->
  </process>
  <process host="Jean_Yves" function="bittorrent.Peer">
    <argument value="00000003"/>         <!-- my id -->
    <argument value="5000" />         <!-- end time -->
  </process>
  <process host="TeX" function="bittorrent.Peer">
    <argument value="00000004"/>   <!-- my id -->
    <argument value="5000" />   <!-- end time -->
  </process>
  <process host="Geoff" function="bittorrent.Peer">
    <argument value="00000005"/>     <!-- my id -->
    <argument value="5000" />     <!-- end time -->
  </process>
  <process host="Disney" function="bittorrent.Peer">
    <argument value="00000006"/>      <!-- my id -->
    <argument value="5000" />      <!-- end time -->
  </process>
  <process host="iRMX" function="bittorrent.Peer">
    <argument value="00000007"/>    <!-- my id -->
    <argument value="5000" />    <!-- end time -->
  </process>
  <process host="McGee" function="bittorrent.Peer">
    <argument value="00000008"/>     <!-- my id -->
    <argument value="5000" />     <!-- end time -->
  </process>
</platform>

=== simgrid/simgrid/examples/platforms/small_platform_with_failures.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <AS  id="AS0"  routing="Full">
    <host id="Tremblay" speed="25Mf"/>
    <host id="Jupiter" speed="25Mf" state_file="jupiter_state.trace"/>
    <host id="Fafard" speed="25Mf" state_file="fafard_state.trace" />
    <host id="Ginette" speed="25Mf" state_file="ginette_state.trace"/>
    <host id="Bourassa" speed="25Mf"state_file="bourassa_state.trace"/>

    <link id="1" bandwidth="1MBps" latency="0"/>
    <link id="2" bandwidth="1MBps" latency="0"/>
    <link id="3" bandwidth="1MBps" latency="0" state_file="link3_state.trace" />
    <link id="4" bandwidth="1MBps" latency="0" state_file="link4_state.trace" />
    <link id="5" bandwidth="1MBps" latency="0"/>
    <link id="6" bandwidth="1MBps" latency="0"/>
    <link id="7" bandwidth="1MBps" latency="0"/>
    <link id="8" bandwidth="1MBps" latency="0"/>
    <link id="9" bandwidth="1MBps" latency="0"/>
    <link id="10" bandwidth="1MBps" latency="0"/>
    <link id="loopback_FATPIPE" bandwidth="10MBps" latency="0" sharing_policy="FATPIPE"/>
    <link id="loopback" bandwidth="100MBps" latency="0"/>

    <route src="Tremblay" dst="Tremblay"><link_ctn id="loopback"/></route>
    <route src="Jupiter" dst="Jupiter"><link_ctn id="loopback"/></route>
    <route src="Fafard" dst="Fafard"><link_ctn id="loopback"/></route>
    <route src="Ginette" dst="Ginette"><link_ctn id="loopback"/></route>
    <route src="Bourassa" dst="Bourassa"><link_ctn id="loopback"/></route>
    <route src="Tremblay" dst="Jupiter"><link_ctn id="1"/></route>
    <route src="Tremblay" dst="Fafard"><link_ctn id="2"/></route>
    <route src="Tremblay" dst="Ginette"><link_ctn id="3"/></route>
    <route src="Tremblay" dst="Bourassa"><link_ctn id="4"/></route>
    <route src="Jupiter" dst="Fafard"><link_ctn id="5"/></route>
    <route src="Jupiter" dst="Ginette"><link_ctn id="6"/></route>
    <route src="Jupiter" dst="Bourassa"><link_ctn id="7"/></route>
    <route src="Fafard" dst="Ginette"><link_ctn id="8"/></route>
    <route src="Fafard" dst="Bourassa"><link_ctn id="9"/></route>
    <route src="Ginette" dst="Bourassa"><link_ctn id="10"/></route>
  </AS>
</platform>

=== simgrid/simgrid/teshsuite/simdag/platforms/Dijkstra.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
 <AS id="AS0" routing="Dijkstra">
   <host id="NODO01" speed="10Mf"/>
   <host id="NODO02" speed="10Mf"/>

   <router id="ROUTER"/>

   <link id="1" bandwidth="1MBps" latency="1ms"/>
   <link id="2" bandwidth="1MBps" latency="1ms"/>

   <link id="10" bandwidth="1MBps" latency="1ms"/>
   <link id="11" bandwidth="1MBps" latency="1ms"/>
   <link id="12" bandwidth="1MBps" latency="1ms"/>

   <route src="NODO01" dst="ROUTER" symmetrical="NO"><link_ctn id="1"/></route>
   <route src="NODO02" dst="ROUTER" symmetrical="NO"><link_ctn id="2"/></route>

   <route src="ROUTER" dst="NODO01" symmetrical="NO"><link_ctn id="1"/></route>
   <route src="ROUTER" dst="NODO02" symmetrical="NO"><link_ctn id="2"/></route>

   <route src="NODO01" dst="NODO02" symmetrical="NO">
     <link_ctn id="10"/><link_ctn id="11"/><link_ctn id="12"/>
   </route>
 </AS>
</platform>

=== simgrid/simgrid/src/bindings/ruby/basic_platform.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "simgrid.dtd">
 <platform version="2">
 <AS  id="AS0"  routing="Full">
   <!-- ljlkj -->
   <host id="Tremblay" power="98095000"/>
   <host id="Jupiter" power="76296000"/>
   <host id="Fafard" power="76296000"/>
   <host id="Ginette" power="48492000"/>
   <host id="Bourassa" power="48492000"/>
   <link id="6" bandwidth="41279125" latency="5.9904e-05"/>
   <link id="11" bandwidth="252750" latency="0.00570455"/>
   <link id="3" bandwidth="34285625" latency="0.000514433"/>
   <link id="7" bandwidth="11618875" latency="0.00018998"/>
   <link id="9" bandwidth="7209750" latency="0.001461517"/>
   <link id="12" bandwidth="1792625" latency="0.007877863"/>
   <link id="2" bandwidth="118682500" latency="0.000136931"/>
   <link id="8" bandwidth="8158000" latency="0.000270544"/>
   <link id="1" bandwidth="34285625" latency="0.000514433"/>
   <link id="4" bandwidth="10099625" latency="0.00047978"/>
   <link id="0" bandwidth="41279125" latency="5.9904e-05"/>
   <link id="10" bandwidth="4679750" latency="0.000848712"/>
   <link id="5" bandwidth="27946250" latency="0.000278066"/>
   <link id="loopback" bandwidth="498000000" latency="0.000015" sharing_policy="FATPIPE"/>
   <route src="Tremblay" dst="Tremblay"><link_ctn id="loopback"/></route>
   <route src="Jupiter" dst="Jupiter"><link_ctn id="loopback"/></route>
   <route src="Fafard" dst="Fafard"><link_ctn id="loopback"/></route>
   <route src="Ginette" dst="Ginette"><link_ctn id="loopback"/></route>
   <route src="Bourassa" dst="Bourassa"><link_ctn id="loopback"/></route>
   <route src="Tremblay" dst="Jupiter">
     <link_ctn id="9"/>
   </route>
   <route src="Tremblay" dst="Fafard">
     <link_ctn id="4"/><link_ctn id="3"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="8"/>
   </route>
   <route src="Tremblay" dst="Ginette">
     <link_ctn id="4"/><link_ctn id="3"/><link_ctn id="5"/>
   </route>
   <route src="Tremblay" dst="Bourassa">
     <link_ctn id="4"/><link_ctn id="3"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="6"/><link_ctn id="7"/>
   </route>
   <route src="Jupiter" dst="Tremblay">
     <link_ctn id="9"/>
   </route>
   <route src="Jupiter" dst="Fafard">
     <link_ctn id="9"/><link_ctn id="4"/><link_ctn id="3"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="8"/>
   </route>
   <route src="Jupiter" dst="Ginette">
     <link_ctn id="9"/><link_ctn id="4"/><link_ctn id="3"/><link_ctn id="5"/>
   </route>
   <route src="Jupiter" dst="Bourassa">
     <link_ctn id="9"/><link_ctn id="4"/><link_ctn id="3"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="6"/><link_ctn id="7"/>
   </route>
   <route src="Fafard" dst="Tremblay">
     <link_ctn id="8"/><link_ctn id="1"/><link_ctn id="0"/><link_ctn id="2"/><link_ctn id="3"/><link_ctn id="4"/>
   </route>
   <route src="Fafard" dst="Jupiter">
     <link_ctn id="8"/><link_ctn id="1"/><link_ctn id="0"/><link_ctn id="2"/><link_ctn id="3"/><link_ctn id="4"/><link_ctn id="9"/>
   </route>
   <route src="Fafard" dst="Ginette">
     <link_ctn id="8"/><link_ctn id="1"/><link_ctn id="0"/><link_ctn id="2"/><link_ctn id="5"/>
   </route>
   <route src="Fafard" dst="Bourassa">
     <link_ctn id="8"/><link_ctn id="6"/><link_ctn id="7"/>
   </route>
   <route src="Ginette" dst="Tremblay">
     <link_ctn id="5"/><link_ctn id="3"/><link_ctn id="4"/>
   </route>
   <route src="Ginette" dst="Jupiter">
     <link_ctn id="5"/><link_ctn id="3"/><link_ctn id="4"/><link_ctn id="9"/>
   </route>
   <route src="Ginette" dst="Fafard">
     <link_ctn id="5"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="8"/>
   </route>
   <route src="Ginette" dst="Bourassa">
     <link_ctn id="5"/><link_ctn id="2"/><link_ctn id="0"/><link_ctn id="1"/><link_ctn id="6"/><link_ctn id="7"/>
   </route>
   <route src="Bourassa" dst="Tremblay">
     <link_ctn id="7"/><link_ctn id="6"/><link_ctn id="1"/><link_ctn id="0"/><link_ctn id="2"/><link_ctn id="3"/><link_ctn id="4"/>
   </route>
   <route src="Bourassa" dst="Jupiter">
     <link_ctn id="7"/><link_ctn id="6"/><link_ctn id="1"/><link_ctn id="0"/><link_ctn id="2"/><link_ctn id="3"/><link_ctn id="4"/><link_ctn id="9"/>
   </route>
   <route src="Bourassa" dst="Fafard">
     <link_ctn id="7"/><link_ctn id="6"/><link_ctn id="8"/>
   </route>
   <route src="Bourassa" dst="Ginette">
     <link_ctn id="7"/><link_ctn id="6"/><link_ctn id="1"/><link_ctn id="0"/><link_ctn id="2"/><link_ctn id="5"/>
   </route>
 </AS>
 </platform>

=== simgrid/simgrid/examples/msg/mc/chord/deploy_chord_before_dsend_liveness.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">

  <process host="Gatien" function="node">
    <argument value="48"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="4"/>        <!-- time to sleep before it starts-->
    <argument value ="60"/>		<!-- deadline -->
  </process>

  <process host="McGee" function="node">
    <argument value="42"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="3"/>        <!-- time to sleep before it starts-->
    <argument value ="60"/>		<!-- deadline -->
  </process>

  <process host="Geoff" function="node">
    <argument value="32"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="10"/>         <!-- time to sleep before it starts-->
    <argument value ="60"/>            <!-- deadline -->
  </process>
  
   <process host="Jacquelin" function="node">
    <argument value="1"/>         <!-- my id -->
    <argument value ="60"/>             <!-- deadline -->
   </process>

</platform>

=== simgrid/simgrid/examples/platforms/energy_platform.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "https://simgrid.org/simgrid.dtd">
<platform version="4.1">
  <zone id="AS0" routing="Full">
    <!-- Multiple pstate processor capacities can be defined as a list of powers specified for a given host -->
    <!-- Attribute 'pstate' specifies the initialy selected pstate (here, the lowest pstate corresponds to the highest
         processor speed) -->
    <host id="MyHost1" speed="100.0Mf,50.0Mf,20.0Mf" pstate="0" core="4" >
      <!--  List of Idle:OneCore:AllCores (in Watts) corresponding to the speed consumed when the processor is idle
            and when one core is at full speed, and when all cores are fully loaded -->
      <!--  The list must contain one energetic profile for each previously defined pstate-->
      <prop id="watt_per_state" value="100.0:120.0:200.0, 93.0:110.0:170.0, 90.0:105.0:150.0" />
      <prop id="watt_off" value="10" />
    </host>
    
    <host id="MyHost2" speed="100.0Mf,50.0Mf,20.0Mf" pstate="0" core="1" >
      <!-- This host is mono-core, so AllCores=OneCore and is omitted -->
      <prop id="watt_per_state" value="100.0:200.0, 93.0:170.0, 90.0:150.0" />
      <prop id="watt_off" value="10" />
    </host>
    
    <host id="MyHost3" speed="100.0Mf,50.0Mf,20.0Mf" pstate="0" core="1" >
      <!-- This host is mono-core, so AllCores=OneCore and is omitted -->
      <prop id="watt_per_state" value="100.0:200.0, 93.0:170.0, 90.0:150.0" />
      <prop id="watt_off" value="10" />
    </host>
 
    <link id="bus" bandwidth="100kBps" latency="0" sharing_policy="SHARED">
<!--   REALISTIC VALUES                    <prop id="watt_range" value="10.3581:10.7479" /> -->
<!--  IREALISTIC VALUES FOR THE TEST -->   <prop id="watt_range" value="1:3" /> 
    </link>
    <route src="MyHost1" dst="MyHost2">
      <link_ctn id="bus"/>
    </route>
    <route src="MyHost1" dst="MyHost3">
      <link_ctn id="bus"/>
    </route>
    <route src="MyHost2" dst="MyHost3">
      <link_ctn id="bus"/>
    </route>
  </zone>
</platform>

=== simgrid/simgrid/examples/platforms/tag_config.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
	
<config id="General">
	<prop id="maxmin/precision" value="0.000010"></prop>
	<prop id="cpu/optim" value="TI"></prop>
	<prop id="workstation/model" value="compound"></prop>
	<prop id="network/model" value="SMPI"></prop>
	<prop id="path" value="~/"></prop>
	<prop id="smpi/bw_factor" value="65472:0.940694;15424:0.697866;9376:0.58729"></prop>
</config>
	
<AS  id="AS0"  routing="Full">
   <host id="bob" power="1000000000"/>
   <host id="alice" power="500000000"/>
 
   <link id="link1" bandwidth="125000000" latency="5E-5"/>
   <link id="link2" bandwidth="125000000" latency="5E-5"/>
   <link id="link3" bandwidth="125000000" latency="5E-5"/>
   
   <route src="bob" dst="alice" symmetrical="YES">
     <link_ctn id="link1"/>
	 <link_ctn id="link2"/>
	 <link_ctn id="link3"/>
   </route>
</AS>
</platform>
